[package]
name = "quotick"
version = "0.1.0"
authors = ["19h <kenan@sig.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
btree = { path = "./btree", version = "0.1.0" }
byteorder = "1.4.3"
memmap = "0.7.0"
serde = "1.0.129"
serde_derive = "1.0.129"
uuid = "0.8.2"
