[package]
name = "quotick"
version = "0.1.0"
authors = ["19h <kenan@sig.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
serde = "1.0.128"
serde_derive = "1.0.128"
